### ISSUE TITLE
Quick concerns

### ISSUE THREAD

**Issue by RohanAlexander** [taliafabs/USPresidentialPollingForecast2024#3]
- R is appropriately cited (1/1)
	- Great.
- Data are appropriately cited (1/1)
	- Great.
- Class paper (1/1)
	- Great.
- LLM usage is documented (1/1)
	- Great.
- Title (1/2)
	- Change title to something like "Forecasting the 2024 US Presidential Election"
	- Subtitle needs to be a little more concise. 
- Author, date, and repo (0/2)
	- Date is wrong - just change line 9 in the quarto doc to the same that I use in the starter folder so that it updated automatically.
- Abstract (4/4)
	- Great.
- Introduction (3/4)
	- Is there are missing "On" at the start of the introduction?
	- Other than that great.
- Estimand (0/1)
	- Could not find this.
- Data (0/10)
	- Not completed.
- Measurement (2/4)
	- We are trying to measure someone's opinion and then translate that into who will win an election. That's the fundamental measurement task and I don't see this addressed here.
- Model (5/10)
	- Not completed, but what is there is good.
- Results (5/10)
	- Not completed, but what is there is good.
- Discussion (0/10)
	- Not completed.
- Prose (3/6)
	- Please do not use words/phrases that I asked you not to use.
- Cross-references (1/1)
	- Great.
- Captions (2/2)
	- Great.
- Graphs/tables/etc (-/4)
	- You don't need both titles and captions. Just add the title into the caption content.
- Idealized methodology (5/10)
	- I need you to define these terms to show me that you understand them. What is a sampling frame?
- Idealized survey (2/4)
	- Not yet complete, but what is there is good.
- Pollster methodology overview and evaluation (-/10)
	- Same comment as Idealized methodology.
	- Make sure you define terms so that I know that you know what they are.
- Referencing (4/4)
	- Great.
- Commits (0/2)
	- It's weird that your co-authors don't have any commits. I'm guessing they're going to do other stuff and this will be resolved by the final submission.
- Sketches (2/2)
	- Great.
- Simulation (4/4)
	- Great.
- Tests-simulation (3/4)
	- Be more sophisticated.
- Tests-actual (3/4)
	- Be more sophisticated.
- Parquet (1/1)
	- Great.
- Reproducible workflow (3/4)
	- Don't forget to remove "Some checks" in the README.
	- Remove files/folders that you're not using e.g. datasheets.
	- Don't forget to comment and close all Issues after you address them
- Miscellaneous (2/3)
	- Figures 4 and 5 are delightful.
	- Drop down for state was a great idea.

**Comment by taliafabs** [comment]
Thank you for the feedback! We really appreciated it.
